### ISSUE TITLE
Can't install in python 2.7.15

### ISSUE THREAD

**Issue by jvines** [adrn/TwoBody#9]
Running pip install twobody yields the following:

It seems the function invalidate_caches is no longer available in python 2.7.15 and thus, twobody cannot be installed..

Collecting twobody
  Using cached https://files.pythonhosted.org/packages/96/7e/5a63dd91f13f8c41f81601a011f0d6990b697ae436c60a8d4ce1f202444f/twobody-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_d/dsf3j7cs2x93bdljc73ljslm0000gn/T/pip-install-dT6MhF/twobody/setup.py", line 18, in <module>
        from astropy_helpers.setup_helpers import (register_commands, get_debug_option,
      File "/private/var/folders/_d/dsf3j7cs2x93bdljc73ljslm0000gn/T/pip-install-dT6MhF/twobody/astropy_helpers/astropy_helpers/setup_helpers.py", line 25, in <module>
        from .distutils_helpers import (add_command_option, get_compiler_option,
      File "/private/var/folders/_d/dsf3j7cs2x93bdljc73ljslm0000gn/T/pip-install-dT6MhF/twobody/astropy_helpers/astropy_helpers/distutils_helpers.py", line 18, in <module>
        from .utils import silence
      File "/private/var/folders/_d/dsf3j7cs2x93bdljc73ljslm0000gn/T/pip-install-dT6MhF/twobody/astropy_helpers/astropy_helpers/utils.py", line 23, in <module>
        from importlib import invalidate_caches
    ImportError: cannot import name invalidate_caches

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_d/dsf3j7cs2x93bdljc73ljslm0000gn/T/pip-install-dT6MhF/twobody/

**Comment by adrn** [comment]
Sorry for missing this. Unfortunately the packages is Python 3 only.
